// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"global_vars","status":true,"description":"Define global variables and constants","parameters":{}},
{"name":"util","status":true,"description":"Common utilities","parameters":{}},
{"name":"SnakeGame","status":true,"description":"Snake Game Core","parameters":{}},
{"name":"rpg_overrides","status":true,"description":"Built-in RPG function overrides","parameters":{}}
];
